### ISSUE TITLE
Scrub deck doesn't scrub it clean

### ISSUE THREAD

**Issue by j-hui** [cs3157/boatswain#7]
For some reason, `scrub-deck.py` (in #6 ) takes a few tries to actually get (and delete) all the repos. Not clear if this is an issue with `.getRepos()` or something but this is something that needs fixing at the end of the semester.

**Comment by hmontero1205** [comment]
Resolved here:
https://github.com/cs3157/boatswain/commit/42be5b4db4dfc5b28f33cce9075fc53e616c08b6
