### ISSUE TITLE
Python throws DeprecationWarning when parsing csv argument

### ISSUE THREAD

**Issue by nsgomez** [cs3157/boatswain#8]
https://github.com/cs3157/boatswain/blob/c02de2c155b4e5aa7fa4094a617e2c941d28841d/canvas-wrangler.py#L48

>`/usr/lib/python3.6/argparse.py:1196: DeprecationWarning: 'U' mode is deprecated`

Replacing this with 'r' seems to be enough to fix it.

**Comment by j-hui** [comment]
fixed in #6
